server:
  port: 8082
  servlet:
    contextPath: /sportNutrition
spring:
  datasource:
    password: MyPass
    url: jdbc:mysql://localhost:3306/online_nutrition_store?user=root
    driverClassName: com.mysql.cj.jdbc.Driver