server:
  port: 8082
  servlet:
    contextPath: /atomic-bear
spring:
  datasource:
    password: _Unbreakable**Pwd_
    url: jdbc:mysql://localhost:3306/online_nutrition_store?user=root
    driverClassName: com.mysql.cj.jdbc.Driver